jobs:
  wait-for-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Request User Approval
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.html_url }} \
          --body "Please approve the build by commenting `/approve-build`."

      - name: Wait for User Response
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while true; do
            RESPONSE=$(gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments --jq '.[].body' | grep "/approve-build" || true)
            if [[ "$RESPONSE" != "" ]]; then
              echo "Build approved!"
              break
            fi
            echo "Waiting for approval..."
            sleep 10
          done
